export const translations = {
  en: {
    party: 'PARTY',
    item: 'ITEM',
    qty: 'QUANTITY',
    city: 'CITY',
    selectLabels: 'SELECT LABELS',
    preview: 'PREVIEW',
    print: 'PRINT',
    exportPdf: 'EXPORT PDF',
    languages: 'SELECT LANGUAGES',
    english: 'English',
    hindi: 'Hindi',
    tamil: 'Tamil',
    telugu: 'Telugu',
    marathi: 'Marathi',
    gujarati: 'Gujarati',
    kannada: 'Kannada',
    odisha: 'Odia',
    filterByCity: 'FILTER BY CITY',
    filterByParty: 'FILTER BY PARTY',
    filterByItem: 'FILTER BY ITEM',
    clearFilters: 'CLEAR FILTERS',
    selectAll: 'SELECT ALL',
    deselectAll: 'DESELECT ALL',
  },

  hi: {
    party: 'पार्टी',
    item: 'आइटम',
    qty: 'क्वांटिटी',
    city: 'सिटी',
    selectLabels: 'सेलेक्ट लेबल्स',
    preview: 'प्रीव्यू',
    print: 'प्रिंट',
    exportPdf: 'एक्सपोर्ट पीडीएफ',
    languages: 'सेलेक्ट लैंग्वेजेस',
    english: 'इंग्लिश',
    hindi: 'हिंदी',
    tamil: 'तमिल',
    telugu: 'तेलुगु',
    marathi: 'मराठी',
    gujarati: 'गुजराती',
    kannada: 'कन्नड़',
    odisha: 'ओडिया',
    filterByCity: 'फिल्टर बाय सिटी',
    filterByParty: 'फिल्टर बाय पार्टी',
    filterByItem: 'फिल्टर बाय आइटम',
    clearFilters: 'क्लियर फिल्टर्स',
    selectAll: 'सेलेक्ट ऑल',
    deselectAll: 'डीसेलेक्ट ऑल',
  },

  ta: {
    party: 'பார்ட்டி',
    item: 'ஐடம்',
    qty: 'குவாண்டிட்டி',
    city: 'சிட்டி',
    selectLabels: 'செலக்ட் லேபல்ஸ்',
    preview: 'பிரிவ்யூ',
    print: 'பிரிண்ட்',
    exportPdf: 'எக்ஸ்போர்ட் பி.டி.எஃப்',
    languages: 'செலக்ட் லாங்குவேஜஸ்',
    english: 'இங்கிலிஷ்',
    hindi: 'ஹிந்தி',
    tamil: 'தமிழ்',
    telugu: 'தெலுங்கு',
    marathi: 'மராத்தி',
    gujarati: 'குஜராத்தி',
    kannada: 'கன்னட',
    odisha: 'ஒடியா',
    filterByCity: 'பில்டர் பை சிட்டி',
    filterByParty: 'பில்டர் பை பார்ட்டி',
    filterByItem: 'பில்டர் பை ஐடம்',
    clearFilters: 'க்ளியர் பில்டர்ஸ்',
    selectAll: 'செலக்ட் ஆல்',
    deselectAll: 'டீசெலக்ட் ஆல்',
  },

  te: {
    party: 'పార్టీ',
    item: 'ఐటమ్',
    qty: 'క్వాంటిటీ',
    city: 'సిటీ',
    selectLabels: 'సెలెక్ట్ లేబుల్స్',
    preview: 'ప్రివ్యూ',
    print: 'ప్రింట్',
    exportPdf: 'ఎక్స్‌పోర్ట్ పీడీఎఫ్',
    languages: 'సెలెక్ట్ లాంగ్వేజెస్',
    english: 'ఇంగ్లీష్',
    hindi: 'హిందీ',
    tamil: 'తమిళ్',
    telugu: 'తెలుగు',
    marathi: 'మరాఠీ',
    gujarati: 'గుజరాతీ',
    kannada: 'కన్నడ',
    odisha: 'ఒడియా',
    filterByCity: 'ఫిల్టర్ బై సిటీ',
    filterByParty: 'ఫిల్టర్ బై పార్టీ',
    filterByItem: 'ఫిల్టర్ బై ఐటమ్',
    clearFilters: 'క్లియర్ ఫిల్టర్స్',
    selectAll: 'సెలెక్ట్ ఆల్',
    deselectAll: 'డీసెలెక్ట్ ఆల్',
  },

  mr: {
    party: 'पार्टी',
    item: 'आयटम',
    qty: 'क्वांटिटी',
    city: 'सिटी',
    selectLabels: 'सेलेक्ट लेबल्स',
    preview: 'प्रीव्यू',
    print: 'प्रिंट',
    exportPdf: 'एक्सपोर्ट पीडीएफ',
    languages: 'सेलेक्ट लँग्वेजेस',
    english: 'इंग्लिश',
    hindi: 'हिंदी',
    tamil: 'तमिळ',
    telugu: 'तेलुगू',
    marathi: 'मराठी',
    gujarati: 'गुजराती',
    kannada: 'कन्नड',
    odisha: 'ओडिया',
    filterByCity: 'फिल्टर बाय सिटी',
    filterByParty: 'फिल्टर बाय पार्टी',
    filterByItem: 'फिल्टर बाय आयटम',
    clearFilters: 'क्लियर फिल्टर्स',
    selectAll: 'सेलेक्ट ऑल',
    deselectAll: 'डीसेलेक्ट ऑल',
  },

  gu: {
    party: 'પાર્ટી',
    item: 'આઇટમ',
    qty: 'ક્વોન્ટિટી',
    city: 'સિટી',
    selectLabels: 'સિલેક્ટ લેબલ્સ',
    preview: 'પ્રિવ્યુ',
    print: 'પ્રિન્ટ',
    exportPdf: 'એક્સપોર્ટ પીડીએફ',
    languages: 'સિલેક્ટ લેંગ્વેજેસ',
    english: 'ઇંગ્લિશ',
    hindi: 'હિન્દી',
    tamil: 'તમિલ',
    telugu: 'તેલુગુ',
    marathi: 'મરાઠી',
    gujarati: 'ગુજરાતી',
    kannada: 'કન્નડ',
    odisha: 'ઓડિયા',
    filterByCity: 'ફિલ્ટર બાય સિટી',
    filterByParty: 'ફિલ્ટર બાય પાર્ટી',
    filterByItem: 'ફિલ્ટર બાય આઇટમ',
    clearFilters: 'ક્લિયર ફિલ્ટર્સ',
    selectAll: 'સિલેક્ટ ઓલ',
    deselectAll: 'ડીસિલેક્ટ ઓલ',
  },

  kn: {
    party: 'ಪಾರ್ಟಿ',
    item: 'ಐಟಂ',
    qty: 'ಕ್ವಾಂಟಿಟಿ',
    city: 'ಸಿಟಿ',
    selectLabels: 'ಸೆಲೆಕ್ಟ್ ಲೇಬಲ್ಸ್',
    preview: 'ಪ್ರಿವ್ಯೂ',
    print: 'ಪ್ರಿಂಟ್',
    exportPdf: 'ಎಕ್ಸ್‌ಪೋರ್ಟ್ ಪಿಡಿಎಫ್',
    languages: 'ಸೆಲೆಕ್ಟ್ ಲ್ಯಾಂಗ್ವೇಜಸ್',
    english: 'ಇಂಗ್ಲಿಷ್',
    hindi: 'ಹಿಂದಿ',
    tamil: 'ತಮಿಳು',
    telugu: 'ತೆಲುಗು',
    marathi: 'ಮರಾಠಿ',
    gujarati: 'ಗುಜರಾತಿ',
    kannada: 'ಕನ್ನಡ',
    odisha: 'ಒಡಿಯಾ',
    filterByCity: 'ಫಿಲ್ಟರ್ ಬೈ ಸಿಟಿ',
    filterByParty: 'ಫಿಲ್ಟರ್ ಬೈ ಪಾರ್ಟಿ',
    filterByItem: 'ಫಿಲ್ಟರ್ ಬೈ ಐಟಂ',
    clearFilters: 'ಕ್ಲಿಯರ್ ಫಿಲ್ಟರ್ಸ್',
    selectAll: 'ಸೆಲೆಕ್ಟ್ ಆಲ್',
    deselectAll: 'ಡಿಸೆಲೆಕ್ಟ್ ಆಲ್',
  },

  od: {
    party: 'ପାର୍ଟି',
    item: 'ଆଇଟମ',
    qty: 'କ୍ୱାଣ୍ଟିଟି',
    city: 'ସିଟି',
    selectLabels: 'ସେଲେକ୍ଟ ଲେବେଲ୍ସ',
    preview: 'ପ୍ରିଭ୍ୟୁ',
    print: 'ପ୍ରିଣ୍ଟ',
    exportPdf: 'ଏକ୍ସପୋର୍ଟ ପିଡିଏଫ',
    languages: 'ସେଲେକ୍ଟ ଲାଙ୍ଗୁଏଜେସ୍',
    english: 'ଇଂଲିଶ୍',
    hindi: 'ହିନ୍ଦୀ',
    tamil: 'ତାମିଲ୍',
    telugu: 'ତେଲୁଗୁ',
    marathi: 'ମରାଠୀ',
    gujarati: 'ଗୁଜରାଟି',
    kannada: 'କନ୍ନଡ',
    odisha: 'ଓଡିଆ',
    filterByCity: 'ଫିଲ୍ଟର ବାୟ ସିଟି',
    filterByParty: 'ଫିଲ୍ଟର ବାୟ ପାର୍ଟି',
    filterByItem: 'ଫିଲ୍ଟର ବାୟ ଆଇଟମ',
    clearFilters: 'କ୍ଲିୟର ଫିଲ୍ଟର୍ସ',
    selectAll: 'ସେଲେକ୍ଟ ଅଲ୍',
    deselectAll: 'ଡିସେଲେକ୍ଟ ଅଲ୍',
  }
};

export const languageNames = {
  en: 'English',
  hi: 'हिंदी (Hindi)',
  ta: 'தமிழ் (Tamil)',
  te: 'తెలుగు (Telugu)',
  mr: 'मराठी (Marathi)',
  gu: 'ગુજરાતી (Gujarati)',
  kn: 'ಕನ್ನಡ (Kannada)',
  od: 'ଓଡ଼ିଆ (Odisha)',
};
