export const translations = {
  en: {
    party: 'PARTY',
    item: 'ITEM',
    qty: 'QUANTITY',
    city: 'CITY',
    selectLabels: 'SELECT LABELS',
    preview: 'PREVIEW',
    print: 'PRINT',
    exportPdf: 'EXPORT PDF',
    languages: 'SELECT LANGUAGES',
    english: 'English',
    hindi: 'Hindi',
    tamil: 'Tamil',
    telugu: 'Telugu',
    marathi: 'Marathi',
    gujarati: 'Gujarati',
    kannada: 'Kannada',
    odisha: 'Odia',
    filterByCity: 'FILTER BY CITY',
    filterByParty: 'FILTER BY PARTY',
    filterByItem: 'FILTER BY ITEM',
    clearFilters: 'CLEAR FILTERS',
    selectAll: 'SELECT ALL',
    deselectAll: 'DESELECT ALL',
  },

  hi: {
    party: 'पार्टी',
    item: 'आइटम',
    qty: 'क्वांटिटी',
    city: 'सिटी',
    selectLabels: 'सेलेक्ट लेबल्स',
    preview: 'प्रीव्यू',
    print: 'प्रिंट',
    exportPdf: 'एक्सपोर्ट पीडीएफ',
    languages: 'सेलेक्ट लैंग्वेजेस',
    english: 'इंग्लिश',
    hindi: 'हिंदी',
    odisha: 'ओडिया',
    filterByCity: 'फिल्टर बाय सिटी',
    filterByParty: 'फिल्टर बाय पार्टी',
    filterByItem: 'फिल्टर बाय आइटम',
    clearFilters: 'क्लियर फिल्टर्स',
    selectAll: 'सेलेक्ट ऑल',
    deselectAll: 'डीसेलेक्ट ऑल',
  },

  od: {
    party: 'ପାର୍ଟି',
    item: 'ଆଇଟମ',
    qty: 'କ୍ୱାଣ୍ଟିଟି',
    city: 'ସିଟି',
    selectLabels: 'ସେଲେକ୍ଟ ଲେବେଲ୍ସ',
    preview: 'ପ୍ରିଭ୍ୟୁ',
    print: 'ପ୍ରିଣ୍ଟ',
    exportPdf: 'ଏକ୍ସପୋର୍ଟ ପିଡିଏଫ',
    languages: 'ସେଲେକ୍ଟ ଲାଙ୍ଗୁଏଜେସ୍',
    english: 'ଇଂଲିଶ୍',
    hindi: 'ହିନ୍ଦୀ',
    odisha: 'ଓଡିଆ',
    filterByCity: 'ଫିଲ୍ଟର ବାୟ ସିଟି',
    filterByParty: 'ଫିଲ୍ଟର ବାୟ ପାର୍ଟି',
    filterByItem: 'ଫିଲ୍ଟର ବାୟ ଆଇଟମ',
    clearFilters: 'କ୍ଲିୟର ଫିଲ୍ଟର୍ସ',
    selectAll: 'ସେଲେକ୍ଟ ଅଲ୍',
    deselectAll: 'ଡିସେଲେକ୍ଟ ଅଲ୍',
  }
};

export const languageNames = {
  en: 'English',
  hi: 'हिंदी (Hindi)',
  od: 'ଓଡ଼ିଆ (Odisha)',
};


